### PR TITLE
Changes for python3

### LINKED ISSUE #1: AttributeError: module 'optimus' has no attribute 'Api'
Hi, the code is pretty simple so i have no idea why it's not working.

I tried simply this code : 
```
import optimus

api = optimus.Api('myapikey')

api.optimize('image.jpg')
```

and i got this error : 

> AttributeError: module 'optimus' has no attribute 'Api'

I'm using python 3.5.2

Thanks in advance for the help

### PR DESCRIPTION
**Pull request by dramaturg**
This fixes #1 
- adjusted module import for python3
- be more loose with the requests dependency
- set classifiers to exclude python versions prior to 2.7

### CODE REVIEW

**Comment by foufrix** [comment]
I tried and it still does not work after reinstalling with pip, still same error

**Comment by dramaturg** [comment]
It works fine over here with your version of python:
```
Python 3.5.2 (default, Jan 18 2017, 02:49:23)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import optimus
>>> api = optimus.Api('xxx')
>>> res = api.optimize('/t/test.png')
>>>
```

Please double-check that you have indeed the latest version of the module (`pip3 list` should show 0.4).

**Comment by foufrix** [comment]
Hi again,

I tried again and effectively i was still on 0.3 yesterday now 0.4 install ok.

But still, the code is running but it's like nothing happen.

I tried with several png and jpg and at the end the file have the same size, here is my code : 

`import optimus
from pathlib import Path


api = optimus.Api('mykey')

file = Path() / 'rnc.png'  # or Path('./doc.txt')
size = file.stat().st_size
print(size)

api.optimize('rnc.png')

size = file.stat().st_size
print(size)`

**Comment by dramaturg** [comment]
`api.optimize` returns the optimized image - it doesn't overwrite the file by itself. Check `example.py`.
(The readme could be improved a bit ...)

A short example:
```
Python 3.5.2 (default, Jan 18 2017, 02:49:23)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import optimus
>>> from pathlib import Path
>>>
>>> api = optimus.Api('xxx')
>>> file = Path('/t/test.jpg')
>>> file.stat().st_size
1718594
>>> res = api.optimize(str(file))
>>> with open('/t/test_out.jpg', 'wb') as o:
...   o.write(res)
...
1645691
>>>
>>> file = Path('/t/test_out.jpg')
>>> file.stat().st_size
1645691
>>>
```

**Comment by foufrix** [comment]
Hello, 

It's working but i actually get file bigger than before or with same size, i was aiming to use it mainly on icons but it look like it does not improve the size.

**Comment by dramaturg** [comment]
This is likely because we optimize for speed of image loading versus pure size optimization (progressive jpegs).

For any questions not directly tied to this python code, please contact our support at hello@keycdn.com.

**Pull request merged**
